# Generated by Django 5.1.1 on 2025-05-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mapping',
            new_name='Mappings',
        ),
    ]
