# Generated by Django 5.1.1 on 2025-05-07 05:58

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_rename_mapping_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, null=True, region=None),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, null=True, region=None),
        ),
    ]
